### ISSUE TITLE
Java Exercise 2.1 - Main and Inheritance

### ISSUE THREAD

**Issue by vinceynhz** [CarterLankford/MentorExercises#21]
This exercise has a different dynamic from previous ones. The intention of this one is to develop some intuition about inheritance when having multiple levels and how inherited methods behave.

The narrative of this exercise can be found here:

https://docs.google.com/document/d/1gwuLsT9wsY7snAVC-wFz3Z-vbVt9-fgS0lj8NqQHQ1I/edit?usp=sharing

You will be creating a few classes so you can add a new folder under `MentorExercises` to contain these.

**Comment by CarterLankford** [comment]
Adding in a comment to respond to the questions on the narrative. The same responses have been added to the code for easy reference. 

1.C: greets shows "Hi! I'm a grandparent", "Hi! I'm a parent", "Hi! I'm a child", for abuelo, padre, hijo respectivly. Which was the expected result
1.D: padre gets its waveOff method from the Grandparent class. Parent extends from the Grandparent class and inherits its mehods. 
2.C: georges waveOff prints "See you later!" which is the expected result. 
2.D: The code does compile. Since george was declared the type Human and a new Child instance was created, george is able to be instantiated to the Child class since Child is a decendant of the Human class.
2.E: The methods called are from the child class since george was instantiated to Child. 
2.F: The code does compile. Since george was declared the type Human and a new Parent instance was created, george is able to be instantiated to the Parent class since Parent is a decendant of the Human class.
2.G: The greet method is from the Parent class since george was instantiated to Parent. But the waveOff method is from the Grandparent class since Parent inherits its methods from Grandparent class. The only reason greet doesn't do the same is because the method has been overriden. 
2.J: The output is greet:"Hi! I'm a child", waveOff:"Ciao!" which is the expected result from the Child class. 
2.K: This code will not compile, since ada was declared Child it is not able to be instantiated to an instance of a parent class. 
3.F: speak methods print "I, a human, was asked to be creative", "I, a parent, was asked to be creative", "I, a human, was asked to be creative" for vicente, trish, aman respectivly; which is the output I was expecting. aman has the speak method from the human class. aman was declared with the type Grandparent, Grandparent's speak method is inherited from the Human class since it doesn't have one of it's own to override.  All three are considered people since they all were initialized in classes that are decendants of the People interface.
3.H: This code does compile. vicente is declared as Human which implements from the People interface which allows it to be instantiated.
3.I: This code does compile. vicente is declared as Human and then instantiated as the type People. Since People is an interface the speak method is abstract and will come from the Human class. 
3.J: This code does not complie since People doesn't have a method for greet. 
3.K: This code does compile. aman was declared as Grandparent, which extends Human that implements People. 
3.L: The speak method prints "I, a human, was asked to be creative", which is the expected result. Since Grandparent doesn't have a method to override speak it uses the method provided by the parent Human class.
